soft_force_pid:
  ros__parameters:
    kp: 0.6
    ki: 0.05
    kd: 0.01
    rate_hz: 50.0
    u_min: -1.0
    u_max: 1.0
    topic_Fc_d: /soft/Fc_d
    topic_Fc_act: /soft/Fc_act
    topic_cmd: /soft/contact_force_cmd

cable_force_pid:
  ros__parameters:
    kp: 0.6
    ki: 0.05
    kd: 0.01
    rate_hz: 50.0
    u_min: -1.0
    u_max: 1.0
    topic_Fc_d: /cable/Fc_d
    topic_Fc_act: /cable/Fc_act
    topic_cmd: /cable/contact_force_cmd

pump_pid_controller:
  ros__parameters:
    kp: 0.8
    ki: 0.1
    kd: 0.02
    rate_hz: 50.0
    u_min: 0.0
    u_max: 1.0
    topic_p_d: /soft/p_d
    topic_p_act: /soft/p_act
    topic_pwm: /soft/pump_pwm

pump_bangbang_controller:
  ros__parameters:
    deadband: 0.02
    topic_p_d: /soft/p_d
    topic_p_act: /soft/p_act
    topic_on: /soft/pump_on
